cors:
  originPatterns: http://localhost:3000,http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bookstore
      username: root
      password: 1234
  jpa:
    hibermate:
      ddl-auto: none
    generate-ddl: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
springdoc:
  pathToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true